### PR TITLE
Add MapFields transformation

### PR DESCRIPTION
**Pull request by KPilnacek**
New feature: https://github.com/python-bonobo/bonobo/issues/285

### CODE REVIEW

**Comment by KPilnacek** [comment]
Transformation factory that maps `function` on the values of a row.
It can be applied either to
1. all columns (`key=True`),
2. no column (`key=False`), or
3. a subset of columns by passing a callable, which takes column name and returns `bool`
 (same as the parameter `function` in `filter`).

:param function: callable
:param key: bool or callable
:return: callable

**Comment by KPilnacek** [comment]
@hartym I came up with a better solution that even allows to use map on `tuple`. The only restriction is that you cannot use the `key` as a callable with `tuple`.

**Comment by KPilnacek** [comment]
by the way, I'll squash it as soon as you are OK with that :-)

**Comment by hartym** [comment]
I'm not sure there is a need to squash the commits, I'll try to have a look very soon.

**Comment by KPilnacek** [comment]
It's up to you, I usually squash them to have a nicer history.

**Comment by hartym** [comment]
LGTM, thanks again for your contribution. No need to squash imho.

**Pull request merged**
