### PR TITLE
Feature/pass env vars at runtime

### PR DESCRIPTION
**Pull request by cw-andrews**
***I created a new job in the tests/util directory so I could verify that the passed variables were set and usable in the ETL job itself. I wasn't sure if there was a better way to do this and didn't want to muck things up in the examples directory by creating a new test job there. Please let me know if you think there is a better way to do it, etc.

### CODE REVIEW

**Comment by cw-andrews** [comment]
@hartym,

I don't mean to be a bother but are you planning on accepting this?

Thanks, CW

**Comment by hartym** [comment]
Hello, sorry for the delay.

I'll be back in Paris tomorrow (currently in vacations), with better access to internet / computers, and will look at it then.

Sorry for the delay and thanks for the PR !

**Comment by cw-andrews** [comment]
Romain,

Thanks, didn't mean to interrupt your vacation. I just want to work on some other things regarding the project per the issues list (closing bugs, improving documentation, and adding features) but wanted to make sure this gets integrated first. 

I will work on getting that added to the docs and hope to hear from you soon.

**Comment by hartym** [comment]
Small comment : new features should be developed against develop branch. No action required on your side, I'm currently testing/reviewing against it but just saying so you know PRs should be opened against develop.

**Comment by hartym** [comment]
Checklist:

- [ ] Open PR against python-bonobo/bonobo:develop
- [ ] Move `tests/util/get_passed_env.py` into examples
- [ ] Documentation page about passing env. That can be a new `docs/guide/environment.rst` (or something else if you think of a better name) file, that will be linked from the main guide index.

For now, I merge it in my own develop, because it should not break anything.

**Comment by hartym** [comment]
Merged in develop.

**Pull request closed without merging**
