### PR TITLE
Add internal locking to bonobo.config.services.Exclusive.

### LINKED ISSUE #308: Possible race in implementation of `Exclusive`
I believe there's a race condition in the implementation of `bonobo.config.services.Exclusive`. When a new lock needs to be created, the code makes two accesses to the `Exclusive._locks` dictionary: a read to test for the lock's presence, and then a write to create the new lock. These two accesses are not protected by an internal lock, and open the possibility that two threads might end up creating two different locks for the same resource.

https://github.com/python-bonobo/bonobo/blob/5924de6a124ef7d38d73495132e7f206817e74c5/bonobo/config/services.py#L155-L156

### PR DESCRIPTION
**Pull request by kasei**
This should fix #308. However, I'm unable to get the unit tests running locally due to problems installing Jupyter.

### CODE REVIEW

**Comment by hartym** [comment]
Looks good, a few details :

- "lock" is a bit generic as a name, maybe this attribute should be less exposed (start with _ to mark as "internal")and a bit more explicit. What about "_locks_creation_lock" or something similar ?
- We can use locks as context managers, the code should be a bit more readable (with lock: ...).

Can you make the changes ? I'll test it against some code I have that use this (mostly Google API related code) and merge if I can't find issues.

Thanks !

**Comment by kasei** [comment]
Apologies. I don't do a lot of work in Python, so the Pythonic style often isn't my first approach.

**Comment by hartym** [comment]
No worries, it's very fine to iterate a bit. LGTM, will test it as soon as I'm on a workable device.

Thanks for your contribution!

**Comment by hartym** [comment]
This will be merged with #310 (develop) and #311 (backport to master) when CI has passed.

**Pull request merged**
