### PR TITLE
Fix bonobo init should work on an empty existing directory

### LINKED ISSUE #187: [cli] bonobo init should work on an empty existing directory
```
$ bonobo init .
Traceback (most recent call last):
  File "/Users/rd/bdk/.virtualenvs/3.6/bin/bonobo", line 11, in <module>
    load_entry_point('bonobo', 'console_scripts', 'bonobo')()
  File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/commands/__init__.py", line 35, in entrypoint
    commands[args.pop('command')](**args)
  File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/commands/init.py", line 13, in execute
    checkout=branch
  File "/Users/rd/bdk/.virtualenvs/3.6/lib/python3.6/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/Users/rd/bdk/.virtualenvs/3.6/lib/python3.6/site-packages/cookiecutter/generate.py", line 269, in generate_files
    overwrite_if_exists
  File "/Users/rd/bdk/.virtualenvs/3.6/lib/python3.6/site-packages/cookiecutter/generate.py", line 209, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "." directory already exists
```

### PR DESCRIPTION
**Pull request by arimbr**
Sets cookiecutter [overwrite_if_exists](http://cookiecutter.readthedocs.io/en/latest/_modules/cookiecutter/main.html?highlight=overwrite_if_exists) parameter to True if the current working directory is empty when running `bonobo init .`.

Fixes #187

### CODE REVIEW

**Comment by arimbr** [comment]
@hartym
What do you think about this solution?
Should some comment, documentation or test be added for this case?

Running `bonobo init .` from a non empty directory will still ouput:

```
(venv) ari@ari-toshiba:~/Temp/bonobo$  (feature/bonobo-init-should-work-on-an-empty-existing-directory *)$ bonobo init .
Traceback (most recent call last):
  File "/home/ari/Temp/bonobo/venv/bin/bonobo", line 11, in <module>
    load_entry_point('bonobo', 'console_scripts', 'bonobo')()
  File "/home/ari/Temp/bonobo/bonobo/commands/__init__.py", line 35, in entrypoint
    commands[args.pop('command')](**args)
  File "/home/ari/Temp/bonobo/bonobo/commands/init.py", line 19, in execute
    overwrite_if_exists=overwrite
  File "/home/ari/Temp/bonobo/venv/lib/python3.6/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/home/ari/Temp/bonobo/venv/lib/python3.6/site-packages/cookiecutter/generate.py", line 269, in generate_files
    overwrite_if_exists
  File "/home/ari/Temp/bonobo/venv/lib/python3.6/site-packages/cookiecutter/generate.py", line 209, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "." directory already exists
```
Should a custom exception be raised instead to inform that the current directory is not empty?

**Comment by hartym** [comment]
The solution looks fine. As far as I remember, there is no test case yet for "Bonobo init", it would be awesome if you can add a test case for both new directory and empty existing directory. There is little chance that the code would break as it is, but it will be very useful for the day an enhancement is added to init, as it will also serve as a reminder of the expected behaviour. Thanks!

**Comment by arimbr** [comment]
I added tests for init a new directory  (`bonobo init project-name`) and init within an empty existing directory (`bonobo init .`). I only tested for the output, is it a good idea to test the content of the directory here?

There is a third case that is not supported as of now:
```
mkdir foo
bonobo init foo
```
This will still raise an exception because the current fix checks whether the current directory is empty and not the directory where to create project. What do you think about this case?

**Comment by hartym** [comment]
Looks fine but a few details:

- We definitely don't want to test on the content of the directory, but asserting it exist and actually contain something (maybe anything within `bonobo.commands.run.DEFAULT_GRAPH_FILENAMES`) would be better, as for now the test does not check it actually did anything.
- Creating and deleting files in test should probably be a bit more "sandboxed", I think it's better practice to use a temporary directory for this (instead of playing within whatever the cwd is). Pytest provides a `tmpdir` fixture for that (https://docs.pytest.org/en/latest/tmpdir.html).

Can you add this to the patch?

**Comment by arimbr** [comment]
Thanks for your comments and the link to pytest :) I agree with the sandboxes approach.

I will fix those incosistencies. Regarding the option overwrite_if_exists, having it as an argument may polute the simplicity of the current command line. I will give it a second thought.

**Comment by hartym** [comment]
> Regarding the option overwrite_if_exists, having it as an argument may polute the simplicity of the current command line. I will give it a second thought.

Agreed, not really useful in fact.

**Comment by arimbr** [comment]
@hartym

**Comment by hartym** [comment]
No idea about the failing test, but it's likely it's not related, let's wait a bit as "nightly" can sometimes (even if rare) have issues.

The other issue I did not think about beforehand is that this test is really slow. I tried to make it faster by merging two of your tests to avoid one init, and using a single runner on that but I'm not very satisfied. I'll probably try to mock a bit of things in cookiecutter to speed that up before merging.

**Comment by hartym** [comment]
(PS @arimbr can you merge hartym:arimbr-feature/bonobo-init-should-work-on-an-empty-existing-directory in your PR ? Maybe I'm unable to use github correctly but did not find how I could update a PR that I don't own).

**Comment by hartym** [comment]
Restarted the build, just to see if it changes anything.

**Comment by arimbr** [comment]
@hartym Thanks! Good point with the init tests being slow.

I merged your branch here.

I am not sure either what is the proper way to handle PR publicly. I was expecting you to be able to push to this branch. Just in case I added you as a collaborator to arimbr/bonobo, would that allow you to push to this branch? https://github.com/arimbr/bonobo/invitations

**Comment by arimbr** [comment]
Based on https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ you should be able to add new commits to this branch.
screenshot-github com-2017-10-24-15-14-29-480

For that, I think you have to add git@github.com:arimbr/bonobo.git as a remote, and then you should be able to push to that remote feature branch?

**Pull request merged**
